//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnOOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thi
    {
        public string MaMonHoc { get; set; }
        public string MaHocVien { get; set; }
        public double DiemThi { get; set; }
    
        public virtual HocVien HocVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
